int S1, S2, S3, S4, St;
float Sa;
Console.WriteLine("請輸入第一季的業績 : ");
S1 = int.Parse(Console.ReadLine());
St = S1;
Sa = (float)St / 1;
Console.WriteLine("累積總業績:{0}   平均業績:{1}", St, Sa);
Console.WriteLine("請輸入第二季的業績 : ");
S2 = int.Parse(Console.ReadLine());
St = S1 + S2;
Sa = (float)St / 2;
Console.WriteLine("累積總業績:{0}   平均業績:{1}", St, Sa);
Console.WriteLine("請輸入第三季的業績 : ");
S3 = int.Parse(Console.ReadLine());
St = S1 + S2 + S3;
Sa = (float)St / 3;
Console.WriteLine("累積總業績:{0}   平均業績:{1}", St, Sa);
Console.WriteLine("請輸入第四季的業績 : ");
S4 = int.Parse(Console.ReadLine());
St = S1 + S2 + S3 + S4;
Sa = (float)St / 4;
Console.WriteLine("累積總業績:{0}   平均業績:{1}", St, Sa);
Console.Read();
